// <auto-generated />
using System;
using BrightFocus.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrightFocus.Data.Persistence.Migrations
{
    [DbContext(typeof(BrightFocusDbContext))]
    [Migration("20241024162031_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BrightFocus.Core.Domain.Inventory.Chemicals", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(35);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(29);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(32);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(39);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(40);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(43);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(37);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(31);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(34);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(44);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<double>("ExportDateTs")
                        .HasColumnType("double")
                        .HasColumnOrder(8);

                    b.Property<string>("FactoryImport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(7);

                    b.Property<double>("ImportDateTs")
                        .HasColumnType("double")
                        .HasColumnOrder(9);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(38);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(41);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(36);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(42);

                    b.Property<string>("ManufacturingPlant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(6);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(2);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(12);

                    b.Property<string>("ReceiptExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(11);

                    b.Property<string>("ReceiptImport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(10);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(30);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(33);

                    b.Property<string>("Uses")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnOrder(3);

                    b.Property<int>("Volume")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Chemicals");
                });

            modelBuilder.Entity("BrightFocus.Core.Domain.Inventory.Fiber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(5);

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(37);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(31);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(34);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(41);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(42);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(45);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(39);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(33);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(36);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(46);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<string>("FactoryExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(14);

                    b.Property<string>("FactoryImport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(13);

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(9);

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(40);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(43);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(38);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(44);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(10);

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(2);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<string>("ReceiptExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(12);

                    b.Property<string>("ReceiptImport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(11);

                    b.Property<int>("TotalVolume")
                        .HasColumnType("int")
                        .HasColumnOrder(8);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(32);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(35);

                    b.Property<int>("Volume")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.ToTable("Fiber");
                });

            modelBuilder.Entity("BrightFocus.Core.Domain.Inventory.FinishProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClothId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("ClothType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(3);

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(38);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(32);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(35);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(42);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(43);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(46);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(40);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(34);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(37);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(47);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<double>("ExportDateTs")
                        .HasColumnType("double")
                        .HasColumnOrder(11);

                    b.Property<string>("FactoryImport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(10);

                    b.Property<double>("ImportDateTs")
                        .HasColumnType("double")
                        .HasColumnOrder(12);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(41);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(44);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(39);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(45);

                    b.Property<string>("ManufacturingPlant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(9);

                    b.Property<int>("MeterOfCloth")
                        .HasColumnType("int")
                        .HasColumnOrder(8);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(15);

                    b.Property<int>("NumberOfCloth")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<string>("ReceiptExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(14);

                    b.Property<string>("ReceiptImport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(13);

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<string>("Spindle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnOrder(5);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(33);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(36);

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.ToTable("FinishProduct");
                });

            modelBuilder.Entity("BrightFocus.Core.Domain.Inventory.PaperTube", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(37);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(31);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(34);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(41);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(42);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(45);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(39);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(33);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(36);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(46);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<double>("ExportDateTs")
                        .HasColumnType("double")
                        .HasColumnOrder(10);

                    b.Property<string>("FactoryImport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(9);

                    b.Property<double>("ImportDateTs")
                        .HasColumnType("double")
                        .HasColumnOrder(11);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(40);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(43);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(38);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(44);

                    b.Property<string>("ManufacturingPlant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnOrder(2);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(14);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<string>("ReceiptExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(13);

                    b.Property<string>("ReceiptImport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(12);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnOrder(3);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnOrder(5);

                    b.Property<decimal>("UnitPriceVat")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnOrder(7);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(32);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(35);

                    b.Property<double>("Vat")
                        .HasColumnType("double")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.ToTable("PaperTube");
                });

            modelBuilder.Entity("BrightFocus.Core.Domain.Inventory.WastesProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClothId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("ClothType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(3);

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(38);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(32);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(35);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(42);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(43);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(46);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(40);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(34);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(37);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(47);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<double>("ExportDateTs")
                        .HasColumnType("double")
                        .HasColumnOrder(11);

                    b.Property<string>("FactoryImport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(10);

                    b.Property<double>("ImportDateTs")
                        .HasColumnType("double")
                        .HasColumnOrder(12);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(41);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(44);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(39);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(45);

                    b.Property<string>("ManufacturingPlant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(9);

                    b.Property<int>("MeterOfCloth")
                        .HasColumnType("int")
                        .HasColumnOrder(8);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(15);

                    b.Property<int>("NumberOfCloth")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<string>("ReceiptExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(14);

                    b.Property<string>("ReceiptImport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(13);

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<string>("Spindle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnOrder(5);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(33);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(36);

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.ToTable("WastesProduct");
                });

            modelBuilder.Entity("BrightFocus.Core.Domain.Inventory.Wood", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClothId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("ClothType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(3);

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(38);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(32);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(35);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(42);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(43);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(46);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(40);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(34);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(37);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(47);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<double>("ExportDateTs")
                        .HasColumnType("double")
                        .HasColumnOrder(11);

                    b.Property<string>("FactoryImport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(10);

                    b.Property<double>("ImportDateTs")
                        .HasColumnType("double")
                        .HasColumnOrder(12);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(41);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(44);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(39);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(45);

                    b.Property<string>("ManufacturingPlant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(9);

                    b.Property<int>("MeterOfCloth")
                        .HasColumnType("int")
                        .HasColumnOrder(8);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(15);

                    b.Property<int>("NumberOfCloth")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<string>("ReceiptExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(14);

                    b.Property<string>("ReceiptImport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(13);

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<string>("Spindle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnOrder(6);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(33);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(36);

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.ToTable("Wood");
                });

            modelBuilder.Entity("BrightFocus.Core.Domain.Tasks.TaskList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(31);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(25);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(28);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(35);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(36);

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(6);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(39);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(33);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(27);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(30);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(40);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(5);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(34);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(37);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(32);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(38);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(2);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(7);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(3);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("TaskType")
                        .HasColumnType("int")
                        .HasColumnOrder(8);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(26);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(29);

                    b.HasKey("Id");

                    b.HasIndex("Name", "ProductName");

                    b.ToTable("TaskList");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MLanguage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(28);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(22);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(25);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(32);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(33);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(36);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(30);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(24);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(27);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(37);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(3);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<string>("Icon")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(31);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(34);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(29);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(35);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnOrder(2);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(23);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(26);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MLanguages_Name");

                    b.ToTable("MLanguages");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(27);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(21);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(24);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(31);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(32);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(35);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(29);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(23);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(26);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(36);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(4);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(30);

                    b.Property<bool>("IsGranted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(33);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(28);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(34);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(2);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(22);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(25);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MPermissions_Name");

                    b.ToTable("MPermissions");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnOrder(7);

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(30);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(24);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(27);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(34);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(35);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(38);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(32);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(26);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(29);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(39);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(3);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(33);

                    b.Property<bool>("IsStatic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(36);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(31);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(37);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(2);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(4);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(25);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MRoles_Name");

                    b.ToTable("MRoles");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MRolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(26);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(20);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(23);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(30);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(31);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(34);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(28);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(22);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(25);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(35);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(29);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(32);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(27);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(33);

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(3);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(21);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(24);

                    b.HasKey("Id");

                    b.ToTable("MRolePermissions");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnOrder(10);

                    b.Property<string>("AuthenticationSource")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(28);

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnOrder(20);

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(51);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(45);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(48);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(55);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(56);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(59);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(53);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(47);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(50);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(60);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(3);

                    b.Property<string>("EmailConfirmationCode")
                        .HasMaxLength(328)
                        .HasColumnType("varchar(328)")
                        .HasColumnOrder(7);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<string>("GoogleAuthenticatorKey")
                        .HasColumnType("longtext")
                        .HasColumnOrder(26);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(17);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(54);

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(16);

                    b.Property<bool>("IsLockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(11);

                    b.Property<bool>("IsPhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(13);

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(15);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(57);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(52);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(58);

                    b.Property<DateTime?>("LockoutEndDateUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(9);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(4);

                    b.Property<string>("NormalizedEmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(19);

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(18);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnOrder(6);

                    b.Property<string>("PasswordResetCode")
                        .HasMaxLength(328)
                        .HasColumnType("varchar(328)")
                        .HasColumnOrder(8);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(12);

                    b.Property<int?>("ProfilePictureId")
                        .HasColumnType("int")
                        .HasColumnOrder(22);

                    b.Property<string>("RecoveryCode")
                        .HasColumnType("longtext")
                        .HasColumnOrder(27);

                    b.Property<string>("Salt")
                        .HasColumnType("longtext")
                        .HasColumnOrder(21);

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnOrder(14);

                    b.Property<bool>("ShouldChangePasswordOnNextLogin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(23);

                    b.Property<string>("SignInToken")
                        .HasColumnType("longtext")
                        .HasColumnOrder(25);

                    b.Property<DateTime?>("SignInTokenExpireTimeUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(24);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(5);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(46);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(49);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_MUser_UserName");

                    b.ToTable("MUsers");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(28);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(22);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(25);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(32);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(33);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(36);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(30);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(24);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(27);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(37);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(5);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(31);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(34);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(29);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(35);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(23);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(26);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<long?>("UserLinkId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_MUserAccount_UserName");

                    b.ToTable("MUserAccounts");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(27);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(21);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(24);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(31);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(32);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(35);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(29);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(23);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(26);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(36);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(30);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(33);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(28);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(34);

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnOrder(3);

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(4);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(22);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(25);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_MUserLogin_UserId");

                    b.ToTable("MUserLogins");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserLoginAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BrowserInfo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnOrder(6);

                    b.Property<string>("ClientIpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(4);

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnOrder(5);

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(30);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(24);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(27);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(34);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(35);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(38);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(32);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(26);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(29);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(39);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(33);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(36);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(31);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(37);

                    b.Property<byte>("Result")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnOrder(7);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(25);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(28);

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("UserNameOrEmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("UserNameOrEmailAddress")
                        .HasDatabaseName("IX_MUserLoginAttempt_UserNameOrEmailAddress");

                    b.ToTable("MUserLoginAttempts");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(3);

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(26);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(20);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(23);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(30);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(31);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(34);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(28);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(22);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(25);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(35);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(29);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(32);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(27);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(33);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(21);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(24);

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("MUserRoles");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(29);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(23);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(26);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(33);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(34);

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(37);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(31);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(25);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(28);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(38);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(32);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(35);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(30);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(36);

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(4);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(24);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(27);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("LoginProvider")
                        .HasDatabaseName("IX_MUserToken_LoginProvider");

                    b.ToTable("MUserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
