// <auto-generated />
using System;
using BrightFocus.Data.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrightFocus.Data.Persistance.Migrations
{
    [DbContext(typeof(BrightFocusDbContext))]
    [Migration("20241002154537_initDb")]
    partial class initDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BrightFocus.Core.Domain.Inventory.Chemicals", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<double>("ExportDateTs")
                        .HasColumnType("double");

                    b.Property<string>("FactoryImport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("ImportDateTs")
                        .HasColumnType("double");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<string>("ManufacturingPlant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ReceiptExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReceiptImport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.Property<string>("Uses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ManufacturingPlant", "FactoryImport", "ReceiptImport", "ReceiptExport");

                    b.ToTable("Chemicals");
                });

            modelBuilder.Entity("BrightFocus.Core.Domain.Inventory.Fiber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<string>("FactoryExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("FactoryImport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quatity")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReceiptImport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TotalVolume")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fiber");
                });

            modelBuilder.Entity("BrightFocus.Core.Domain.Inventory.FinishProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClothId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClothType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<double>("ExportDateTs")
                        .HasColumnType("double");

                    b.Property<string>("FactoryImport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("ImportDateTs")
                        .HasColumnType("double");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<string>("ManufacturingPlant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("MeterOfCloth")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<int>("NumberOfCloth")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReceiptImport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Spindle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FinishProduct");
                });

            modelBuilder.Entity("BrightFocus.Core.Domain.Inventory.PaperTube", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<double>("ExportDateTs")
                        .HasColumnType("double");

                    b.Property<string>("FactoryImport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("ImportDateTs")
                        .HasColumnType("double");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<string>("ManufacturingPlant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Quatity")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReceiptImport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitPriceVat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.Property<double>("Vat")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("PaperTube");
                });

            modelBuilder.Entity("BrightFocus.Core.Domain.Inventory.WasteProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClothId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClothType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<double>("ExportDateTs")
                        .HasColumnType("double");

                    b.Property<string>("FactoryImport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("ImportDateTs")
                        .HasColumnType("double");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<string>("ManufacturingPlant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("MeterOfCloth")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<int>("NumberOfCloth")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReceiptImport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Spindle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WasteProduct");
                });

            modelBuilder.Entity("BrightFocus.Core.Domain.Inventory.Wood", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClothId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClothType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<double>("ExportDateTs")
                        .HasColumnType("double");

                    b.Property<string>("FactoryImport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("ImportDateTs")
                        .HasColumnType("double");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<string>("ManufacturingPlant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("MeterOfCloth")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<int>("NumberOfCloth")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptExport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReceiptImport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Spindle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Wood");
                });

            modelBuilder.Entity("BrightFocus.Core.Domain.Tasks.TaskList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Quatity")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("TaskName", "ProductName");

                    b.ToTable("TaskList");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MLanguage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<string>("Icon")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MLanguages_Name");

                    b.ToTable("MLanguages");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<bool>("IsGranted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MPermissions_Name");

                    b.ToTable("MPermissions");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<bool>("IsStatic")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MRoles_Name");

                    b.ToTable("MRoles");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AuthenticationSource")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("EmailConfirmationCode")
                        .HasMaxLength(328)
                        .HasColumnType("varchar(328)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<string>("GoogleAuthenticatorKey")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<DateTime?>("LockoutEndDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NormalizedEmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("PasswordResetCode")
                        .HasMaxLength(328)
                        .HasColumnType("varchar(328)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("ProfilePictureId")
                        .HasColumnType("int");

                    b.Property<string>("RecoveryCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Salf")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("ShouldChangePasswordOnNextLogin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SignInToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SignInTokenExpireTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_MUser_UserName");

                    b.ToTable("MUsers");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserLinkId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_MUserAccount_UserName");

                    b.ToTable("MUserAccounts");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_MUserLogin_UserId");

                    b.ToTable("MUserLogins");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserLoginAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BrowserInfo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ClientIpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<byte>("Result")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserNameOrEmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserNameOrEmailAddress")
                        .HasDatabaseName("IX_MUserLoginAttempt_UserNameOrEmailAddress");

                    b.ToTable("MUserLoginAttempts");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("MUserRoles");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CreatedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(107);

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(101);

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(104);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(111);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(112);

                    b.Property<double?>("DeletedDateTS")
                        .HasColumnType("double")
                        .HasColumnOrder(109);

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(103);

                    b.Property<string>("DeletedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(106);

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(115);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(116);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(113);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("double")
                        .HasColumnOrder(108);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(114);

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(102);

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(105);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LoginProvider")
                        .HasDatabaseName("IX_MUserToken_LoginProvider");

                    b.ToTable("MUserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
