global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Microsoft.Extensions.DependencyInjection;
global using OpenTelemetry;
global using Microsoft.Extensions.Logging;
global using OpenTelemetry.Trace;
global using Microsoft.Extensions.Hosting;
global using OpenTelemetry.Metrics;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.Diagnostics.HealthChecks;
